services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configServer:
    image: "vishnunarasim/configserver:v8"
    container_name: configServer-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaServer:
    image: "vishnunarasim/eurekaserver:v8.2"
    container_name: eurekaServer-ms
    ports:
      - "8070:8070"
    depends_on:
#      comment rabbitMQ due to memory storage...
#      rabbit:
#        condition: service_healthy
      configServer:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configServer-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accountService:
    image: "vishnunarasim/accountservice:v8"
    container_name: account-ms
    ports:
      - "8080:8080"
    depends_on:
      configServer:
        condition: service_healthy
      eurekaServer:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configServer-config

  loanService:
    image: "vishnunarasim/loanservice:v8"
    container_name: loan-ms
    ports:
      - "9000:9000"
    depends_on:
      configServer:
        condition: service_healthy
      eurekaServer:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configServer-config

  cardService:
    image: "vishnunarasim/cardsservice:v8"
    container_name: card-ms
    ports:
      - "9090:9090"
    depends_on:
      configServer:
        condition: service_healthy
      eurekaServer:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configServer-config

networks:
  bankService:
    driver: "bridge"